### ISSUE TITLE
Header osgEarth/BuildConfig missing in Examples/imgui/SimExamplesGui.h

### ISSUE THREAD

**Issue by urmjs** [USNavalResearchLaboratory/simdissdk#113]
The Examples/imgui/SimExamplesGui.h in current master includes "osgEarth/BuildConfig" which is missing in the current release of SIMDIS_SDK_3rd_win64_vc-14.3.zip . Is there a work-around to build imgui examples with the current pre-built 3rd_party dependencies.

**Comment by emminizer** [comment]
Hello. I just build osgEarth locally on Monday and `osgEarth/BuildConfig` is present. Be sure you're doing a `make install` and building against the installed osgEarth.

See for example: https://github.com/gwaldron/osgearth/blob/master/src/osgEarth/CMakeLists.txt#L938

**Comment by urmjs** [comment]
Thanks @emminizer for the solution. I was looking to know specifically if it would link with the prebuilt 3rd party dependencies at https://github.com/USNavalResearchLaboratory/simdissdk/releases/download/simdissdk-1.20/SIMDIS_SDK_3rd_win64_vc-14.3.zip (i.e, the previous release)

**Comment by emminizer** [comment]
Ah, thanks, I misunderstood.

We definitely try to maintain compatibility with older osgEarth versions. Sometimes osgEarth moves too fast for us to keep up and maintain compatibility. It's a constant fight, especially for a (currently) unfunded requirement. So we do best effort, but are often on the latest osgEarth master.

We generally do not upload "intermediate" 3rd party packs to GitHub because of the size might be fairly large. I am unable to attach it to this issue, as it is 118mb and only 25mb can be posted as an attachment.

In this case, the osgEarth IMGUI support changed pretty drastically. The issue is that osgEarth identifies whether the nodekit is available in a header that was introduced between when IMGUI support changed, and the 1.20 SDK release. Two possible solutions:
* Comment out the include on `osgEarth/BuildConfig`
* Add a `return()` at the top of `SIMDIS_SDK/Examples/imgui/CMakeLists.txt`

Both suggestions are untested on my side, as I'm using the latest master on osgEarth.

**Comment by emminizer** [comment]
The `ImGuiLib` is not an installed resource. It was only intended to support the SIMDIS SDK examples at this time. I welcome a pull request that adds support for `ImGuiLib` to be installed then used in an example similar to `VisExample`.

We currently view this only as sample code to get our examples running and not part of the SDK library itself for internal examples. You are welcome to use ImGui, and reuse the code we have in our examples for your own, provided you follow the correct licensing.
