### ISSUE TITLE
Trying to understand the track preferences

### ISSUE THREAD

**Issue by rmancusi** [USNavalResearchLaboratory/simdissdk#77]
I'm writing a program that adds waypoints to a platform simulator to show the trajectory of an object.  When running, the simulation repeats itself when it gets to the end of the waypoints.

Is there a way to remove the "repeats"?  That is, when the platform gets to the last waypoint I would like for it to stay there instead of repeating the simulation.  I've tried using simUtil::PlatformSimulator::setLoop(bool) to turn that off, but it doesn't give what I want.

Any ideas out there?

**Comment by emminizer** [comment]
Hello, I apologize, this issue slipped through the cracks. I don't check issues often because we primarily rely on the SIMDIS Help Desk, and the email must have slipped through my filters.

simUtil::PlatformSimulator was written specifically to feed demo data for the examples. It is limited in capability. We're certainly willing to accept patches to it, but there may be functionality lapses like what you're seeing.

 - Dan
